inventory:
  size: 3
storage:
  pokemonsPerPage: 24
leveling:
  # In seonds
  experienceGainCooldown: 10
  # Formula: level variabble can be used
  experiencePerMessage: "60"
  # Formula: level variabble can be used
  experiencePerLevel: level * 100
  abilityPointsPerLevel:
    min: 1
    max: 5
